import type { ObscureQuestion, Question } from "../types/index.js";

/**
 * Hardcoded question bank for the prototype.
 * 15 general, 15 geography, 10 science, 10 sport, 10 UK/culture = 60.
 */
export const QUESTIONS: Question[] = [
  // ----- General knowledge (15) -----
  {
    id: "gen-01",
    category: "general",
    prompt: "How many colours are in a rainbow?",
    options: ["Five", "Six", "Seven", "Eight"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "gen-02",
    category: "general",
    prompt: "What is the largest planet in our solar system?",
    options: ["Saturn", "Jupiter", "Neptune", "Earth"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "gen-03",
    category: "general",
    prompt: "Which instrument has 88 keys?",
    options: ["Organ", "Accordion", "Piano", "Harpsichord"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "gen-04",
    category: "general",
    prompt: "What currency is used in Japan?",
    options: ["Won", "Yuan", "Yen", "Ringgit"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "gen-05",
    category: "general",
    prompt: "How many legs does a spider have?",
    options: ["Six", "Eight", "Ten", "Twelve"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "gen-06",
    category: "general",
    prompt: "Who painted the Mona Lisa?",
    options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Botticelli"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "gen-07",
    category: "general",
    prompt: "What is the tallest animal in the world?",
    options: ["Elephant", "Giraffe", "Ostrich", "Polar bear"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "gen-08",
    category: "general",
    prompt: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mercury", "Mars", "Jupiter"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "gen-09",
    category: "general",
    prompt: "How many sides does a hexagon have?",
    options: ["Five", "Six", "Seven", "Eight"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "gen-10",
    category: "general",
    prompt: "What is the hardest natural substance on Earth?",
    options: ["Titanium", "Quartz", "Diamond", "Granite"],
    correctIndex: 2,
    difficulty: "medium",
  },
  {
    id: "gen-11",
    category: "general",
    prompt: "In which year did the Titanic sink?",
    options: ["1905", "1912", "1918", "1923"],
    correctIndex: 1,
    difficulty: "medium",
  },
  {
    id: "gen-12",
    category: "general",
    prompt: "Which language has the most native speakers worldwide?",
    options: ["English", "Hindi", "Spanish", "Mandarin Chinese"],
    correctIndex: 3,
    difficulty: "medium",
  },
  {
    id: "gen-13",
    category: "general",
    prompt: "What does 'www' stand for in a website address?",
    options: ["World Wide Web", "Web World Wide", "Wide World Web", "World Web Wide"],
    correctIndex: 0,
    difficulty: "easy",
  },
  {
    id: "gen-14",
    category: "general",
    prompt: "Which famous ship was captained by Blackbeard?",
    options: ["The Black Pearl", "Queen Anne's Revenge", "The Flying Dutchman", "The Jolly Roger"],
    correctIndex: 1,
    difficulty: "medium",
    tags: ["pirate"],
  },
  {
    id: "gen-15",
    category: "general",
    prompt: "How many minutes are in a full day?",
    options: ["1,440", "1,240", "1,640", "1,040"],
    correctIndex: 0,
    difficulty: "medium",
  },

  // ----- Geography (15) -----
  {
    id: "geo-01",
    category: "geography",
    prompt: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correctIndex: 2,
    difficulty: "medium",
  },
  {
    id: "geo-02",
    category: "geography",
    prompt: "Which is the longest river in the world?",
    options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    correctIndex: 1,
    difficulty: "medium",
  },
  {
    id: "geo-03",
    category: "geography",
    prompt: "Which country has the largest population?",
    options: ["China", "India", "USA", "Indonesia"],
    correctIndex: 1,
    difficulty: "medium",
  },
  {
    id: "geo-04",
    category: "geography",
    prompt: "Mount Everest sits on the border of Nepal and which country?",
    options: ["India", "Bhutan", "China", "Pakistan"],
    correctIndex: 2,
    difficulty: "medium",
  },
  {
    id: "geo-05",
    category: "geography",
    prompt: "What is the smallest country in the world?",
    options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "geo-06",
    category: "geography",
    prompt: "Which ocean is the largest?",
    options: ["Atlantic", "Indian", "Arctic", "Pacific"],
    correctIndex: 3,
    difficulty: "easy",
  },
  {
    id: "geo-07",
    category: "geography",
    prompt: "What is the capital of Canada?",
    options: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    correctIndex: 2,
    difficulty: "medium",
  },
  {
    id: "geo-08",
    category: "geography",
    prompt: "Which desert is the largest hot desert on Earth?",
    options: ["Gobi", "Kalahari", "Sahara", "Mojave"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "geo-09",
    category: "geography",
    prompt: "The Caribbean's famous pirate port, Port Royal, is in which country?",
    options: ["Cuba", "Jamaica", "Haiti", "Bahamas"],
    correctIndex: 1,
    difficulty: "medium",
    tags: ["pirate"],
  },
  {
    id: "geo-10",
    category: "geography",
    prompt: "Which country is shaped like a boot?",
    options: ["Spain", "Greece", "Italy", "Portugal"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "geo-11",
    category: "geography",
    prompt: "What is the capital of Brazil?",
    options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
    correctIndex: 2,
    difficulty: "medium",
  },
  {
    id: "geo-12",
    category: "geography",
    prompt: "Which two countries share the longest international border?",
    options: ["USA & Canada", "Russia & China", "Chile & Argentina", "India & China"],
    correctIndex: 0,
    difficulty: "medium",
  },
  {
    id: "geo-13",
    category: "geography",
    prompt: "In which country would you find the ancient city of Petra?",
    options: ["Egypt", "Jordan", "Morocco", "Turkey"],
    correctIndex: 1,
    difficulty: "hard",
  },
  {
    id: "geo-14",
    category: "geography",
    prompt: "Which European capital is split by the Danube into 'Buda' and 'Pest'?",
    options: ["Vienna", "Prague", "Budapest", "Bratislava"],
    correctIndex: 2,
    difficulty: "medium",
  },
  {
    id: "geo-15",
    category: "geography",
    prompt: "Which country has the most islands in the world?",
    options: ["Indonesia", "Philippines", "Sweden", "Japan"],
    correctIndex: 2,
    difficulty: "hard",
  },

  // ----- Science (10) -----
  {
    id: "sci-01",
    category: "science",
    prompt: "What gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "sci-02",
    category: "science",
    prompt: "What is H2O more commonly known as?",
    options: ["Salt", "Water", "Hydrogen peroxide", "Steam"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "sci-03",
    category: "science",
    prompt: "How many bones are in the adult human body?",
    options: ["186", "206", "226", "246"],
    correctIndex: 1,
    difficulty: "medium",
  },
  {
    id: "sci-04",
    category: "science",
    prompt: "What force keeps us on the ground?",
    options: ["Magnetism", "Friction", "Gravity", "Inertia"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "sci-05",
    category: "science",
    prompt: "Which part of the cell contains DNA?",
    options: ["Cytoplasm", "Nucleus", "Membrane", "Ribosome"],
    correctIndex: 1,
    difficulty: "medium",
  },
  {
    id: "sci-06",
    category: "science",
    prompt: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctIndex: 2,
    difficulty: "medium",
    tags: ["pirate"],
  },
  {
    id: "sci-07",
    category: "science",
    prompt: "Roughly how fast does light travel?",
    options: ["300,000 km/s", "150,000 km/s", "3,000 km/s", "30,000 km/s"],
    correctIndex: 0,
    difficulty: "medium",
  },
  {
    id: "sci-08",
    category: "science",
    prompt: "Which planet has the most moons?",
    options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    correctIndex: 1,
    difficulty: "hard",
  },
  {
    id: "sci-09",
    category: "science",
    prompt: "What kind of animal is a dolphin?",
    options: ["Fish", "Amphibian", "Mammal", "Reptile"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "sci-10",
    category: "science",
    prompt: "What does a barometer measure?",
    options: ["Temperature", "Humidity", "Wind speed", "Air pressure"],
    correctIndex: 3,
    difficulty: "medium",
  },

  // ----- Sport (10) -----
  {
    id: "spo-01",
    category: "sport",
    prompt: "How many players are on a football (soccer) team on the pitch?",
    options: ["9", "10", "11", "12"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "spo-02",
    category: "sport",
    prompt: "In which sport would you perform a slam dunk?",
    options: ["Volleyball", "Basketball", "Netball", "Handball"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "spo-03",
    category: "sport",
    prompt: "How often are the Summer Olympic Games held?",
    options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "spo-04",
    category: "sport",
    prompt: "Which country invented table tennis as a parlour game?",
    options: ["China", "Japan", "England", "USA"],
    correctIndex: 2,
    difficulty: "hard",
  },
  {
    id: "spo-05",
    category: "sport",
    prompt: "What is the maximum break in snooker?",
    options: ["141", "147", "155", "160"],
    correctIndex: 1,
    difficulty: "medium",
  },
  {
    id: "spo-06",
    category: "sport",
    prompt: "In tennis, what score comes after deuce?",
    options: ["Match point", "Game point", "Advantage", "Break point"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "spo-07",
    category: "sport",
    prompt: "Which country has won the most FIFA World Cups?",
    options: ["Germany", "Argentina", "Italy", "Brazil"],
    correctIndex: 3,
    difficulty: "medium",
  },
  {
    id: "spo-08",
    category: "sport",
    prompt: "How long is a marathon?",
    options: ["26.2 miles", "24.2 miles", "28.2 miles", "22.6 miles"],
    correctIndex: 0,
    difficulty: "medium",
  },
  {
    id: "spo-09",
    category: "sport",
    prompt: "In golf, what is one stroke under par called?",
    options: ["Eagle", "Birdie", "Bogey", "Albatross"],
    correctIndex: 1,
    difficulty: "medium",
  },
  {
    id: "spo-10",
    category: "sport",
    prompt: "Which sport uses the term 'checkmate'?",
    options: ["Darts", "Chess", "Fencing", "Poker"],
    correctIndex: 1,
    difficulty: "easy",
  },

  // ----- UK / culture (10) -----
  {
    id: "cul-01",
    category: "culture",
    prompt: "What is the capital of Scotland?",
    options: ["Glasgow", "Aberdeen", "Edinburgh", "Dundee"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "cul-02",
    category: "culture",
    prompt: "Which British band recorded 'Hey Jude'?",
    options: ["The Rolling Stones", "The Beatles", "Queen", "Oasis"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "cul-03",
    category: "culture",
    prompt: "What river flows through London?",
    options: ["Severn", "Mersey", "Thames", "Tyne"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "cul-04",
    category: "culture",
    prompt: "Who wrote 'Romeo and Juliet'?",
    options: ["Charles Dickens", "Jane Austen", "William Shakespeare", "Oscar Wilde"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "cul-05",
    category: "culture",
    prompt: "What is the traditional British dish of battered fish served with?",
    options: ["Rice", "Chips", "Mash", "Salad"],
    correctIndex: 1,
    difficulty: "easy",
  },
  {
    id: "cul-06",
    category: "culture",
    prompt: "Which fictional pirate sails in 'Peter Pan'?",
    options: ["Long John Silver", "Captain Hook", "Captain Flint", "Jack Sparrow"],
    correctIndex: 1,
    difficulty: "easy",
    tags: ["pirate"],
  },
  {
    id: "cul-07",
    category: "culture",
    prompt: "How many countries make up the United Kingdom?",
    options: ["Two", "Three", "Four", "Five"],
    correctIndex: 2,
    difficulty: "easy",
  },
  {
    id: "cul-08",
    category: "culture",
    prompt: "Which artist painted 'The Starry Night'?",
    options: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí"],
    correctIndex: 1,
    difficulty: "medium",
  },
  {
    id: "cul-09",
    category: "culture",
    prompt: "In 'Treasure Island', what marks the treasure on the map?",
    options: ["A skull", "An X", "A flag", "A compass rose"],
    correctIndex: 1,
    difficulty: "easy",
    tags: ["pirate"],
  },
  {
    id: "cul-10",
    category: "culture",
    prompt: "Which streaming-era dance app made sea shanties go viral in 2021?",
    options: ["Snapchat", "Vine", "TikTok", "BeReal"],
    correctIndex: 2,
    difficulty: "medium",
  },
];

/**
 * Obscure Island questions: several options are correct, rarer picks score more.
 * Exactly one option is Fool's Gold — looks obscure and clever, but wrong.
 */
export const OBSCURE_QUESTIONS: ObscureQuestion[] = [
  {
    id: "obs-01",
    prompt: "Name a country whose flag contains the colour red.",
    options: [
      { text: "Japan", correct: true },
      { text: "China", correct: true },
      { text: "Turkey", correct: true },
      { text: "Kiribati", correct: true },
      { text: "Ukraine", correct: false, foolsGold: true },
      { text: "Canada", correct: true },
    ],
  },
  {
    id: "obs-02",
    prompt: "Name a planet with rings.",
    options: [
      { text: "Saturn", correct: true },
      { text: "Jupiter", correct: true },
      { text: "Uranus", correct: true },
      { text: "Neptune", correct: true },
      { text: "Mercury", correct: false, foolsGold: true },
      { text: "None — trick question", correct: false },
    ],
  },
  {
    id: "obs-03",
    prompt: "Name a country that borders France.",
    options: [
      { text: "Spain", correct: true },
      { text: "Belgium", correct: true },
      { text: "Andorra", correct: true },
      { text: "Brazil", correct: true }, // French Guiana border — genuinely obscure!
      { text: "Netherlands", correct: false, foolsGold: true },
      { text: "Germany", correct: true },
    ],
  },
  {
    id: "obs-04",
    prompt: "Name a mammal that can fly or glide.",
    options: [
      { text: "Bat", correct: true },
      { text: "Flying squirrel", correct: true },
      { text: "Colugo", correct: true },
      { text: "Sugar glider", correct: true },
      { text: "Flying fish", correct: false, foolsGold: true },
      { text: "Ostrich", correct: false },
    ],
  },
  {
    id: "obs-05",
    prompt: "Name an element that is a liquid at room temperature.",
    options: [
      { text: "Mercury", correct: true },
      { text: "Bromine", correct: true },
      { text: "Gallium (on a hot day)", correct: true },
      { text: "Caesium (on a hot day)", correct: true },
      { text: "Sodium", correct: false, foolsGold: true },
      { text: "Iron", correct: false },
    ],
  },
  {
    id: "obs-06",
    prompt: "Name a sport that has appeared at the Summer Olympics.",
    options: [
      { text: "Tug of war", correct: true },
      { text: "Skateboarding", correct: true },
      { text: "Breaking (breakdance)", correct: true },
      { text: "Solo synchronised swimming", correct: true },
      { text: "Netball", correct: false, foolsGold: true },
      { text: "Darts", correct: false },
    ],
  },
];

/** Deterministic-friendly helpers (pass rng for tests). */
export function pickQuestions(
  count: number,
  rng: () => number = Math.random,
  exclude: Set<string> = new Set(),
): Question[] {
  const pool = QUESTIONS.filter((q) => !exclude.has(q.id));
  const shuffled = [...pool].sort(() => rng() - 0.5);
  return shuffled.slice(0, count);
}

export function pickObscureQuestion(
  rng: () => number = Math.random,
  exclude: Set<string> = new Set(),
): ObscureQuestion {
  const pool = OBSCURE_QUESTIONS.filter((q) => !exclude.has(q.id));
  const list = pool.length > 0 ? pool : OBSCURE_QUESTIONS;
  const first = list[Math.floor(rng() * list.length)] ?? OBSCURE_QUESTIONS[0];
  return first as ObscureQuestion;
}
