import type { ItemDef, ItemId, Rarity } from "../types/index.js";

/**
 * The final 15 items. Every attack has counterplay (see `counterplay` field
 * and docs/GAME_DESIGN.md). Items marked `simplified` have a documented
 * intended final version.
 */
export const ITEMS: Record<ItemId, ItemDef> = {
  copycat: {
    id: "copycat",
    name: "Copycat",
    icon: "🐱‍👤",
    rarity: "common",
    description: "Copy another pirate's answer. Your answer becomes theirs at the reveal.",
    timing: "lock",
    target: "otherPlayer",
    counterplay: "Pick your target wisely — copy a fool and you sink together.",
    isAttack: false,
  },
  spyglass: {
    id: "spyglass",
    name: "Spyglass",
    icon: "🔭",
    rarity: "common",
    description: "Remove one wrong answer from your view.",
    timing: "question",
    target: "self",
    counterplay: "None needed — non-aggressive scouting tool.",
    isAttack: false,
  },
  luckyDoubloon: {
    id: "luckyDoubloon",
    name: "Lucky Doubloon",
    icon: "🪙",
    rarity: "common",
    description: "If you get this question wrong, gain a small consolation bonus.",
    timing: "reveal",
    target: "self",
    counterplay: "None — a small comeback cushion.",
    isAttack: false,
  },
  fearShot: {
    id: "fearShot",
    name: "Fear Shot",
    icon: "💀",
    rarity: "rare",
    description: "Choose a pirate. Their secret mission bonus is blocked this question.",
    timing: "lock",
    target: "otherPlayer",
    counterplay: "Double Agent protection absorbs it. Captain's Curse reverses it.",
    isAttack: true,
  },
  rumRush: {
    id: "rumRush",
    name: "Rum Rush",
    icon: "🍾",
    rarity: "rare",
    description: "Double your reward on your next correct answer.",
    timing: "question",
    target: "self",
    counterplay: "The risk is yours — answer wrong and the rum was wasted.",
    isAttack: false,
  },
  sabotage: {
    id: "sabotage",
    name: "Sabotage",
    icon: "🪢",
    rarity: "rare",
    description: "Tangle a pirate's rigging: their answer locks in 5 seconds.",
    timing: "question",
    target: "otherPlayer",
    counterplay: "Captain's Curse reverses it. Quick thinkers barely notice.",
    isAttack: true,
  },
  sneaksMap: {
    id: "sneaksMap",
    name: "Sneak's Map",
    icon: "🗺️",
    rarity: "rare",
    description:
      "Mark a wrong answer as a trap. Gain loot for every pirate who falls in — as long as you avoid it yourself.",
    timing: "question",
    target: "wrongOption",
    counterplay: "Mutiny accusations and Fear Shot. Victims who dodge earn a Survivor Chest.",
    isAttack: true,
  },
  treasureSwitch: {
    id: "treasureSwitch",
    name: "Treasure Switch",
    icon: "🔁",
    rarity: "epic",
    description: "Swap your unbanked round loot with another pirate's at the reveal.",
    timing: "lock",
    target: "otherPlayer",
    counterplay: "Banked points are safe. Captain's Curse reverses it.",
    isAttack: true,
  },
  backstab: {
    id: "backstab",
    name: "Backstab",
    icon: "🗡️",
    rarity: "rare",
    description: "Choose a pirate. If they get this question wrong, you gain a bonus.",
    timing: "prep",
    target: "otherPlayer",
    counterplay: "Your target answering correctly wastes the blade.",
    isAttack: true,
  },
  doubleAgent: {
    id: "doubleAgent",
    name: "Double Agent",
    icon: "🎭",
    rarity: "epic",
    description: "Gain a fresh secret mission plus protection from one accusation or Fear Shot.",
    timing: "prep",
    target: "self",
    counterplay: "Suspicious behaviour still draws accusations after the shield breaks.",
    isAttack: false,
  },
  shipwreck: {
    id: "shipwreck",
    name: "Shipwreck",
    icon: "🚢",
    rarity: "epic",
    description: "Choose a pirate. If they answer wrong, they lose their unbanked round loot.",
    timing: "prep",
    target: "otherPlayer",
    counterplay: "Answer correctly, bank early, or hold a Captain's Curse.",
    isAttack: true,
  },
  crownHeist: {
    id: "crownHeist",
    name: "Crown Heist",
    icon: "👑",
    rarity: "legendary",
    description: "Answer correctly to steal 15% of the leader's unprotected score.",
    timing: "final",
    target: "self",
    counterplay: "Banking, Captain's Shield and Captain's Curse blunt the heist.",
    isAttack: true,
  },
  broadsideDuel: {
    id: "broadsideDuel",
    name: "Broadside Duel",
    icon: "💣",
    rarity: "legendary",
    description:
      "Challenge a higher-ranked pirate on this question. Win: +150. The higher-ranked loser risks more.",
    timing: "question",
    target: "higherRanked",
    counterplay: "Knowledge wins duels. Captain's Curse reverses the challenge.",
    isAttack: true,
  },
  blackSpot: {
    id: "blackSpot",
    name: "Black Spot",
    icon: "⚫",
    rarity: "epic",
    description: "Mark a pirate. If they answer wrong, every other pirate gains a bonus.",
    timing: "prep",
    target: "otherPlayer",
    counterplay: "The marked pirate answering correctly tears up the spot.",
    isAttack: true,
  },
  captainsCurse: {
    id: "captainsCurse",
    name: "Captain's Curse",
    icon: "☠️",
    rarity: "legendary",
    description:
      "Ward yourself or an ally. The next attack on them reverses — the attacker's scheme fails and you steal a bonus.",
    timing: "lock",
    target: "anyPlayer",
    counterplay: "Don't attack into it. Bait it out with small plays first.",
    isAttack: false,
  },
};

export const ITEM_LIST = Object.values(ITEMS);

/** Item pools per rarity for chest rolls. */
export const ITEMS_BY_RARITY: Record<Rarity, ItemId[]> = {
  common: ["copycat", "spyglass", "luckyDoubloon"],
  rare: ["fearShot", "rumRush", "sabotage", "sneaksMap", "backstab"],
  epic: ["treasureSwitch", "doubleAgent", "shipwreck", "blackSpot"],
  legendary: ["crownHeist", "broadsideDuel", "captainsCurse"],
};
