import type { ItemDef, ItemId, Rarity } from "../types/index.js";

/**
 * The final 15 items. Every attack has counterplay (see `counterplay` field
 * and docs/GAME_DESIGN.md). Items marked `simplified` have a documented
 * intended final version.
 */
export const ITEMS: Record<ItemId, ItemDef> = {
  copycat: {
    id: "copycat",
    name: "Copycat",
    icon: "🐱‍👤",
    rarity: "common",
    description: "Copy another pirate's answer.",
    timing: "lock",
    target: "otherPlayer",
    counterplay: "Pick your target wisely — copy a fool and you sink together.",
    isAttack: false,
  },
  spyglass: {
    id: "spyglass",
    name: "Spyglass",
    icon: "🔭",
    rarity: "common",
    description: "Remove one wrong answer.",
    timing: "question",
    target: "self",
    counterplay: "None needed — non-aggressive scouting tool.",
    isAttack: false,
  },
  luckyDoubloon: {
    id: "luckyDoubloon",
    name: "Lucky Doubloon",
    icon: "🪙",
    rarity: "common",
    description: "Wrong answer? Get a small bonus anyway.",
    timing: "reveal",
    target: "self",
    counterplay: "None — a small comeback cushion.",
    isAttack: false,
  },
  fearShot: {
    id: "fearShot",
    name: "Fear Shot",
    icon: "💀",
    rarity: "rare",
    description: "Block a pirate's secret mission this question.",
    timing: "lock",
    target: "otherPlayer",
    counterplay: "Double Agent protection absorbs it. Captain's Curse reverses it.",
    isAttack: true,
  },
  rumRush: {
    id: "rumRush",
    name: "Rum Rush",
    icon: "🍾",
    rarity: "rare",
    description: "Double gold on your next correct answer.",
    timing: "question",
    target: "self",
    counterplay: "The risk is yours — answer wrong and the rum was wasted.",
    isAttack: false,
  },
  sabotage: {
    id: "sabotage",
    name: "Sabotage",
    icon: "🪢",
    rarity: "rare",
    description: "Lock a pirate's answer in 5 seconds.",
    timing: "question",
    target: "otherPlayer",
    counterplay: "Captain's Curse reverses it. Quick thinkers barely notice.",
    isAttack: true,
  },
  sneaksMap: {
    id: "sneaksMap",
    name: "Sneak's Map",
    icon: "🗺️",
    rarity: "rare",
    description: "Trap a wrong answer. Earn gold per pirate who picks it.",
    timing: "question",
    target: "wrongOption",
    counterplay: "Mutiny accusations and Fear Shot. Victims who dodge earn a Survivor Chest.",
    isAttack: true,
  },
  treasureSwitch: {
    id: "treasureSwitch",
    name: "Treasure Switch",
    icon: "🔁",
    rarity: "epic",
    description: "Swap round gold with another pirate.",
    timing: "lock",
    target: "otherPlayer",
    counterplay: "Banked points are safe. Captain's Curse reverses it.",
    isAttack: true,
  },
  backstab: {
    id: "backstab",
    name: "Backstab",
    icon: "🗡️",
    rarity: "rare",
    description: "Mark a pirate. If they answer wrong, you profit.",
    timing: "prep",
    target: "otherPlayer",
    counterplay: "Your target answering correctly wastes the blade.",
    isAttack: true,
  },
  doubleAgent: {
    id: "doubleAgent",
    name: "Double Agent",
    icon: "🎭",
    rarity: "epic",
    description: "New secret mission + a shield from one attack.",
    timing: "prep",
    target: "self",
    counterplay: "Suspicious behaviour still draws accusations after the shield breaks.",
    isAttack: false,
  },
  shipwreck: {
    id: "shipwreck",
    name: "Shipwreck",
    icon: "🚢",
    rarity: "epic",
    description: "Mark a pirate. Wrong answer sinks their round gold.",
    timing: "prep",
    target: "otherPlayer",
    counterplay: "Answer correctly, bank early, or hold a Captain's Curse.",
    isAttack: true,
  },
  crownHeist: {
    id: "crownHeist",
    name: "Crown Heist",
    icon: "👑",
    rarity: "legendary",
    description: "Answer right to steal 15% of the leader's gold.",
    timing: "final",
    target: "self",
    counterplay: "Banking, Captain's Shield and Captain's Curse blunt the heist.",
    isAttack: true,
  },
  broadsideDuel: {
    id: "broadsideDuel",
    name: "Broadside Duel",
    icon: "💣",
    rarity: "legendary",
    description: "Duel a pirate above you. Win the question, win +150.",
    timing: "question",
    target: "higherRanked",
    counterplay: "Knowledge wins duels. Captain's Curse reverses the challenge.",
    isAttack: true,
  },
  blackSpot: {
    id: "blackSpot",
    name: "Black Spot",
    icon: "⚫",
    rarity: "epic",
    description: "Mark a pirate. If they answer wrong, everyone else profits.",
    timing: "prep",
    target: "otherPlayer",
    counterplay: "The marked pirate answering correctly tears up the spot.",
    isAttack: true,
  },
  captainsCurse: {
    id: "captainsCurse",
    name: "Captain's Curse",
    icon: "☠️",
    rarity: "legendary",
    description: "Shield a pirate. The next attack on them bounces back.",
    timing: "lock",
    target: "anyPlayer",
    counterplay: "Don't attack into it. Bait it out with small plays first.",
    isAttack: false,
  },
};

export const ITEM_LIST = Object.values(ITEMS);

/** Item pools per rarity for chest rolls. */
export const ITEMS_BY_RARITY: Record<Rarity, ItemId[]> = {
  common: ["copycat", "spyglass", "luckyDoubloon"],
  rare: ["fearShot", "rumRush", "sabotage", "sneaksMap", "backstab"],
  epic: ["treasureSwitch", "doubleAgent", "shipwreck", "blackSpot"],
  legendary: ["crownHeist", "broadsideDuel", "captainsCurse"],
};
